// src/lib/products.ts

export interface ProductColor {
  name: string;
  hex: string;
  image?: string; 
}

export interface Product {
  id: string;
  title: string;
  unit: string;
  thumbnail: string;
  description: string;
  composicion: string;
  gramaje: string;
  ancho: string;
  rendimiento: number;
  prices: {
    menudeo: number;
    mayoreo: number;
  };
  hasRollo: boolean;
  singleColor?: boolean;
  origin?: string;
  category: string;
  colors?: ProductColor[];
  unidadesPorRollo?: number;
}

export const products: Product[] = [
  {
    id: "prod_alaska",
    title: "Alaska",
    unit: "Kilo",
    thumbnail: "/assets/products/alaska/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 175.00, mayoreo: 170.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_andromeda",
    title: "Andromeda",
    unit: "Kilo",
    thumbnail: "/assets/products/andromeda/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_apolo",
    title: "Apolo",
    unit: "Kilo",
    thumbnail: "/assets/products/119.jpg", 
    description: "Resistencia superior a la abrasiÃ³n y el pilling.",
    composicion: "100% PoliÃ©ster",
    gramaje: "150",
    ancho: "1.60m",
    rendimiento: 3.7,
    singleColor: true,
    prices: { menudeo: 160.00, mayoreo: 155.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_ares",
    title: "Ares",
    unit: "Kilo",
    thumbnail: "/assets/products/ares/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_athlos",
    title: "Athlos",
    unit: "Kilo",
    thumbnail: "/assets/products/athlos/blanco.jpg", 
    description: "Versatilidad total para cualquier disciplina deportiva.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true,
    prices: { menudeo: 125.00, mayoreo: 120.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_azucena",
    title: "Azucena",
    unit: "Kilo",
    thumbnail: "/assets/products/azucena/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 95.00, mayoreo: 90.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_brock",
    title: "Brock",
    unit: "Kilo",
    thumbnail: "/assets/products/brock.jpg",
    description: "Versatilidad total para cualquier disciplina deportiva.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true,
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_brush",
    title: "Brush",
    unit: "Kilo",
    thumbnail: "/assets/products/brush/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 120.00, mayoreo: 115.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_capriati",
    title: "Capriati",
    unit: "Kilo",
    thumbnail: "/assets/products/capriati/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_caprice",
    title: "Caprice",
    unit: "Kilo",
    thumbnail: "/assets/products/caprice/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 140.00, mayoreo: 135.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_delta",
    title: "Delta",
    unit: "Kilo",
    thumbnail: "/assets/products/delta/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 175.00, mayoreo: 170.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_diablo",
    title: "Diablo",
    unit: "Metro", 
    unidadesPorRollo: 50, 
    thumbnail: "/assets/products/diablo/negro.jpg", 
    description: "Uso rudo absoluto. Resistente a la abrasiÃ³n, ideal para equipo tÃ¡ctico y calzado.",
    composicion: "100% Nylon Alta Tenacidad", 
    gramaje: "220", 
    ancho: "1.50m",
    rendimiento: 1, 
    singleColor: false, 
    prices: { menudeo: 88.00, mayoreo: 83.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "Telas TÃ©cnicas",
    colors: [
      { name: "Perla", hex: "#EAE0C8", image: "/assets/products/diablo/perla.jpg" },
      { name: "Marino", hex: "#1A243A", image: "/assets/products/diablo/marino.jpg" },
      { name: "Vino", hex: "#5C1527", image: "/assets/products/diablo/vino.jpg" },
      { name: "Blanco", hex: "#F8F9FA", image: "/assets/products/diablo/blanco.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/diablo/azulrey.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/diablo/rojo.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/diablo/negro.jpg" },
      { name: "Oxford", hex: "#3C3C3C", image: "/assets/products/diablo/oxford.jpg" }
    ]
  },
  {
    id: "prod_f30",
    title: "F30",
    unit: "Kilo",
    thumbnail: "/assets/products/F-30/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_felpa_china",
    title: "Felpa China",
    unit: "Kilo", 
    unidadesPorRollo: 25, 
    thumbnail: "/assets/products/felpa_china/marino.jpg", 
    description: "La tela ideal para la confecciÃ³n de sudaderas, pants y ropa deportiva de invierno. Cuenta con una cara lisa y un reverso afelpado que garantiza mÃ¡xima calidez y durabilidad.",
    composicion: "50% AlgodÃ³n / 50% PoliÃ©ster", 
    gramaje: "280", 
    ancho: "1.60m",
    rendimiento: 2.2, 
    singleColor: false, 
    prices: { menudeo: 110.00, mayoreo: 105.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "LÃ­nea Invernal",
    colors: [
      { name: "Marino", hex: "#1A243A", image: "/assets/products/felpa_china/marino.jpg" },
      { name: "Negro", hex: "#111111", image: "/assets/products/felpa_china/negro.jpg" },
      { name: "Blanco", hex: "#F8F9FA", image: "/assets/products/felpa_china/blanco.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/felpa_china/azulrey.jpg" },
      { name: "Vino", hex: "#5C1527", image: "/assets/products/felpa_china/vino.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/felpa_china/rojo.jpg" },
      { name: "Jaspe Perla", hex: "#DCDCDC", image: "/assets/products/felpa_china/jaspe_perla.jpg" },
      { name: "Oxford Jaspe", hex: "#555555", image: "/assets/products/felpa_china/oxfordjaspe.jpg" }
    ]
  },
  {
    id: "prod_felpa_spun",
    title: "Felpa Spun",
    unit: "Kg", 
    unidadesPorRollo: 25, 
    thumbnail: "/assets/products/felpa spun/negro.jpg", 
    description: "Tejido de alto volumen y suavidad excepcional. Ideal para sudaderas y pants de gama premium con excelente retenciÃ³n de calor.",
    composicion: "100% PoliÃ©ster",
    gramaje: "280",
    ancho: "1.90m",
    rendimiento: 2.5, 
    singleColor: false, 
    prices: { menudeo: 110.00, mayoreo: 105.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "LÃ­nea Invernal",
    colors: [
      { name: "Blanco", hex: "#F8F9FA", image: "/assets/products/felpa spun/blanco.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/felpa spun/rojo.jpg" },
      { name: "Marino", hex: "#1A243A", image: "/assets/products/felpa spun/marino.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/felpa spun/negro.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/felpa spun/azulrey.jpg" },
      { name: "Vino", hex: "#5C1527", image: "/assets/products/felpa spun/vino.jpg" }
    ] 
  },
  {
    id: "prod_flanel",
    title: "Flanel",
    unit: "Kilo", 
    unidadesPorRollo: 27, 
    thumbnail: "/assets/products/flanel/blanco.jpg", 
    description: "Nuestra tela Flanel es la reina del invierno. Su textura ultra suave, afelpada y ligera retiene el calor corporal de manera excepcional, haciÃ©ndola la opciÃ³n perfecta para confeccionar pijamas, cobijas, sudaderas y ropa de descanso premium.",
    composicion: "100% PoliÃ©ster", 
    gramaje: "260", 
    ancho: "1.60m",
    rendimiento: 2.4, 
    singleColor: false, 
    prices: { menudeo: 125.00, mayoreo: 120.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "LÃ­nea Invernal",
    colors: [
      { name: "Blanco", hex: "#ffffff", image: "/assets/products/flanel/blanco.jpg" },
      { name: "Vino", hex: "#5C1527", image: "/assets/products/flanel/vino.jpg" },
      { name: "Marino", hex: "#1A243A", image: "/assets/products/flanel/marino.jpg" },
      { name: "Negro", hex: "#111111", image: "/assets/products/flanel/negro.jpg" },
      { name: "Fiusha", hex: "#E01B6A", image: "/assets/products/flanel/fiusha.jpg" },
      { name: "Palo Rosa", hex: "#D69A9A", image: "/assets/products/flanel/palorosa.jpg" },
      { name: "Rosa Pastel", hex: "#F4C2C2", image: "/assets/products/flanel/rosapastel.jpg" }, 
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/flanel/azulrey.jpg" },
      { name: "Naranja", hex: "#FF6F00", image: "/assets/products/flanel/naranja.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/flanel/rojo.jpg" }
    ]
  },
  {
    id: "prod_granizo",
    title: "Granizo",
    unit: "Kilo",
    thumbnail: "/assets/products/granizo/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 115.00, mayoreo: 110.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_horous",
    title: "Horous",
    unit: "Kilo",
    thumbnail: "/assets/products/120.jpg", 
    description: "DiseÃ±o vanguardista para moda deportiva urbana.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.2,
    singleColor: true,
    prices: { menudeo: 160.00, mayoreo: 155.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_inter_70",
    title: "Inter 70",
    unit: "Kilo",
    thumbnail: "/assets/products/inter-70/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 140.00, mayoreo: 135.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_jumanji",
    title: "Jumanji",
    unit: "Kilo",
    thumbnail: "/assets/products/jumanji/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    singleColor: true,
    prices: { menudeo: 145.00, mayoreo: 140.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra"
  },
  {
    id: "prod_kyoto",
    title: "Kyoto",
    unit: "Kilo",
    thumbnail: "/assets/products/116.jpg", 
    description: "Acabado premium con tacto seda y caÃ­da espectacular.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true,
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_licra_liluna",
    title: "Licra Liluna",
    unit: "Kilo",
    thumbnail: "/assets/products/liluna/liluna.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 2.0,
    singleColor: true,
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra"
  },
  {
    id: "prod_licra_playera",
    title: "Licra Playera",
    unit: "Kilo",
    thumbnail: "/assets/products/licra-playera/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    singleColor: true,
    prices: { menudeo: 130.00, mayoreo: 125.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra"
  },
  {
    id: "prod_licra_poliester",
    title: "Licra PoliÃ©ster",
    unit: "Kilo",
    thumbnail: "/assets/products/licra-poliester/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    prices: { menudeo: 145.00, mayoreo: 140.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra",
    colors: [
      { name: "Blanco", hex: "#FFFFFF", image: "/assets/products/licra-poliester/blanco.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/licra-poliester/negro.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/licra-poliester/rojo.jpg" },
      { name: "Rey", hex: "#1434A4", image: "/assets/products/licra-poliester/rey.jpg" },
      { name: "Marino", hex: "#000080", image: "/assets/products/licra-poliester/marino.jpg" }
    ]
  },
  {
    id: "prod_licra_saludable",
    title: "Licra Saludable",
    unit: "Kilo",
    thumbnail: "/assets/products/licra-saludable/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    prices: { menudeo: 140.00, mayoreo: 135.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra",
    colors: [
      { name: "Blanco", hex: "#FFFFFF", image: "/assets/products/licra-saludable/blanco.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/licra-saludable/negro.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/licra-saludable/rojo.jpg" },
      { name: "Rey", hex: "#1434A4", image: "/assets/products/licra-saludable/rey.jpg" },
      { name: "Marino", hex: "#000080", image: "/assets/products/licra-saludable/marino.jpg" },
      { name: "Militar", hex: "#4B5320", image: "/assets/products/licra-saludable/militar.jpg" },
      { name: "Perla Jaspe", hex: "#D9D6D0", image: "/assets/products/licra-saludable/perla-jaspe.jpg" },
      { name: "Oxford Jaspe", hex: "#555555", image: "/assets/products/licra-saludable/oxford-jaspe.jpg" }
    ]
  },
  {
    id: "lycra_metalica",
    title: "Lycra MetÃ¡lica",
    unit: "Metro", 
    unidadesPorRollo: 98, 
    thumbnail: "/assets/products/lycra_metalica/oro.jpg", 
    description: "Licra metÃ¡lica elÃ¡stica con acabado brillante. Ideal para prendas deportivas, escÃ©nicas, de moda, disfraces y usos decorativos.",
    composicion: "100% PoliÃ©ster", 
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 1, 
    singleColor: false, 
    prices: { menudeo: 50.00, mayoreo: 45.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra",
    colors: [
      { name: "Oro MetÃ¡lico", hex: "#D4AF37", image: "/assets/products/lycra_metalica/oro.jpg" },
      { name: "Plata MetÃ¡lica", hex: "#C0C0C0", image: "/assets/products/lycra_metalica/plata.jpg" },
      { name: "Naranja MetÃ¡lico", hex: "#CD7F32", image: "/assets/products/lycra_metalica/bronce.jpg" },
      { name: "Rojo MetÃ¡lico", hex: "#A40000", image: "/assets/products/lycra_metalica/rojo.jpg" },
      { name: "Azul Rey MetÃ¡lico", hex: "#1D3263", image: "/assets/products/lycra_metalica/azulrey.jpg" },
      { name: "TurquÃ©sa MetÃ¡lico", hex: "#8CBED6", image: "/assets/products/lycra_metalica/cielo.jpg" },
      { name: "Perla MetÃ¡lico", hex: "#EAE0C8", image: "/assets/products/lycra_metalica/perla.jpg" },
      { name: "Verde Bandera MetÃ¡lico", hex: "#114232", image: "/assets/products/lycra_metalica/verdebadera.jpg" }, 
      { name: "Verde Manzana MetÃ¡lico", hex: "#8DB600", image: "/assets/products/lycra_metalica/verdemanzana.jpg" },
      { name: "Rosa Pastel MetÃ¡lico", hex: "#F2B8C6", image: "/assets/products/lycra_metalica/rosapastel.jpg" },
      { name: "Fiucha MetÃ¡lico", hex: "#C154C1", image: "/assets/products/lycra_metalica/fiucha.jpg" },
      { name: "Blanco MetÃ¡lico", hex: "#F8F9FA", image: "/assets/products/lycra_metalica/blanco.jpg" },
      { name: "Negro MetÃ¡lico", hex: "#2B2B2C", image: "/assets/products/lycra_metalica/negro.jpg" }
    ]
  },
  {
    id: "prod_madelino",
    title: "Madelino",
    unit: "Kilo",
    thumbnail: "/assets/products/madelino/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_mercury",
    title: "Mercury",
    unit: "Kilo",
    thumbnail: "/assets/products/mercury/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    singleColor: true,
    prices: { menudeo: 160.00, mayoreo: 155.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra"
  },
  {
    id: "prod_micro_estrella",
    title: "Micro Estrella",
    unit: "Kilo",
    thumbnail: "/assets/products/microestrella/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 145.00, mayoreo: 140.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_micro_panal",
    title: "Micro Panal",
    unit: "Kilo",
    thumbnail: "/assets/products/114.jpg", 
    description: "Estructura de panal para mÃ¡xima transpiraciÃ³n y ligereza.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.3,
    prices: { menudeo: 110.00, mayoreo: 105.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n",
    colors: [
      { name: "Blanco", hex: "#FFFFFF", image: "/assets/products/micro-panal/blanco.webp" },
      { name: "Camel", hex: "#C19A6B", image: "/assets/products/micro-panal/camel.png" },
      { name: "Mostaza", hex: "#FFC300", image: "/assets/products/micro-panal/mostaza.png" },
      { name: "Oro Viejo", hex: "#B08D57", image: "/assets/products/micro-panal/oro-viejo.png" },
      { name: "Verde NeÃ³n", hex: "#39FF14", image: "/assets/products/micro-panal/verde-neon.jpg" },
      { name: "Amarillo NeÃ³n", hex: "#CCFF00", image: "/assets/products/micro-panal/amarillo-neon.jpg" },
      { name: "Turquesa", hex: "#40E0D0", image: "/assets/products/micro-panal/turquesa.jpg" },
      { name: "Aqua", hex: "#00FFFF", image: "/assets/products/micro-panal/aqua.jpg" },
      { name: "Militar", hex: "#4B5320", image: "/assets/products/micro-panal/militar.jpg" },
      { name: "Botella", hex: "#006A4E", image: "/assets/products/micro-panal/botella.jpg" },
      { name: "Bandera", hex: "#006847", image: "/assets/products/micro-panal/bandera.jpg" },
      { name: "Menta", hex: "#98FF98", image: "/assets/products/micro-panal/menta.jpg" },
      { name: "Cielo", hex: "#87CEEB", image: "/assets/products/micro-panal/cielo.jpg" },
      { name: "Vino", hex: "#722F37", image: "/assets/products/micro-panal/vino.jpg" },
      { name: "Lila", hex: "#C8A2C8", image: "/assets/products/micro-panal/lila.jpg" },
      { name: "Naranja", hex: "#FF6F00", image: "/assets/products/micro-panal/naranja.jpg" },
      { name: "Gris Baby", hex: "#D3D3D3", image: "/assets/products/micro-panal/gris-baby.jpg" },
      { name: "Uva", hex: "#6F2DA8", image: "/assets/products/micro-panal/uva.jpg" },
      { name: "PetrÃ³leo", hex: "#005F6A", image: "/assets/products/micro-panal/petroleo.jpg" },
      { name: "Palo de Rosa", hex: "#D69A9A", image: "/assets/products/micro-panal/palo-de-rosa.jpg" },
      { name: "Rosa Baby", hex: "#F4C2C2", image: "/assets/products/micro-panal/rosa-baby.jpg" },
      { name: "Magenta", hex: "#FF00FF", image: "/assets/products/micro-panal/magenta.jpg" },
      { name: "Rosa Pastel", hex: "#FFD1DC", image: "/assets/products/micro-panal/rosa-pastel.jpg" },
      { name: "Fiusha", hex: "#FF00CB", image: "/assets/products/micro-panal/fiusha.jpg" },
      { name: "Rosa NeÃ³n", hex: "#FF6EC7", image: "/assets/products/micro-panal/rosa-neon.jpg" },
      { name: "Light Blue", hex: "#ADD8E6", image: "/assets/products/micro-panal/light-blue.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/micro-panal/azul-rey.jpg" },
      { name: "Navy Blue", hex: "#000080", image: "/assets/products/micro-panal/navyblue.jpg" },
      { name: "Oxford", hex: "#494949", image: "/assets/products/micro-panal/oxford.jpg" },
      { name: "Medio", hex: "#808080", image: "/assets/products/micro-panal/medio.jpg" },
      { name: "Perla", hex: "#EAE0C8", image: "/assets/products/micro-panal/perla.jpg" },
      { name: "Mango", hex: "#FFD21C", image: "/assets/products/micro-panal/mango.jpg" },
      { name: "Canario", hex: "#FFE700", image: "/assets/products/micro-panal/canario.jpg" },
      { name: "Caqui", hex: "#C3B091", image: "/assets/products/micro-panal/caqui.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/micro-panal/negro.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/micro-panal/rojo.jpg" },
      { name: "Rey", hex: "#1434A4", image: "/assets/products/micro-panal/rey.jpg" },
      { name: "Azul Francia", hex: "#1F3A93", image: "/assets/products/micro-panal/azul-francia.jpg" }
    ]
  },
  {
    id: "prod_micropique",
    title: "Micro piquÃ©",
    unit: "Kilo",
    thumbnail: "/assets/products/112.jpg", 
    description: "TecnologÃ­a Dry-Fit Calidad Gold. Ideal para uniformes deportivos de alto rendimiento.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.3,
    prices: { menudeo: 100.00, mayoreo: 95.00 },
    hasRollo: true,
    origin: "importado",
    category: "Deportivas / SublimaciÃ³n",
    colors: [
      { name: "Light Navy", hex: "#040C5C", image: "/assets/products/micropique/ligth-navy.jpg" }, 
      { name: "Blanco", hex: "#FFFFFF", image: "/assets/products/micropique/blanco.webp" },
      { name: "Gris Perla", hex: "#E6E6E6", image: "/assets/products/micropique/gris-perla.jpg" },
      { name: "Navy Dark Blue", hex: "#000033", image: "/assets/products/micropique/navydarkblue.jpg" },  
      { name: "Menta", hex: "#82FFF9", image: "/assets/products/micropique/menta.jpg" },
      { name: "Fiusha", hex: "#FF2480", image: "/assets/products/micropique/fiusha.jpg" },
      { name: "Caqui", hex: "#C3B091", image: "/assets/products/micropique/caqui.jpg" },
      { name: "Uva M", hex: "#220038", image: "/assets/products/micropique/uvam.jpg" },
      { name: "Azul Acero", hex: "#4A658F", image: "/assets/products/micropique/azul-acero.jpg" },  
      { name: "Vino", hex: "#722F37", image: "/assets/products/micropique/vino.jpg" },
      { name: "Beige", hex: "#F5F5DC", image: "/assets/products/micropique/beige.jpg" },
      { name: "Camel", hex: "#C19A6B", image: "/assets/products/micropique/camel.jpg" },
      { name: "Gris Medio", hex: "#808080", image: "/assets/products/micropique/gris-medio.jpg" },
      { name: "Oxford", hex: "#494949", image: "/assets/products/micropique/oxford.jpg" },
      { name: "Militar", hex: "#4B5320", image: "/assets/products/micropique/militar.jpg" },
      { name: "Rosa Baby", hex: "#FFDEE6", image: "/assets/products/micropique/rosababy.jpg" },
      { name: "Amarillo Canario", hex: "#FFE600", image: "/assets/products/micropique/amarillo-canario.jpg" },
      { name: "PetrÃ³leo", hex: "#2A3570", image: "/assets/products/micropique/petroleo.jpg" },
      { name: "Rosa Palo", hex: "#D69A9A", image: "/assets/products/micropique/rosapalo.jpg" },
      { name: "Cielo", hex: "#B0EDFF", image: "/assets/products/micropique/cielo.jpg" },
      { name: "Mango", hex: "#FFD21C", image: "/assets/products/micropique/mango.jpg" },
      { name: "Turquesa", hex: "#40E0D0", image: "/assets/products/micropique/turquesa.jpg" },
      { name: "Azul Francia", hex: "#1C86FF", image: "/assets/products/micropique/francia.jpg" },
      { name: "Uva", hex: "#6F2DA8", image: "/assets/products/micropique/uva.jpg" },
      { name: "Bugambilia", hex: "#E0115F", image: "/assets/products/micropique/bugambilia.jpg" },
      { name: "Oro Viejo", hex: "#B08D57", image: "/assets/products/micropique/oro-viejo.jpg" },
      { name: "Mostaza", hex: "#FFC300", image: "/assets/products/micropique/mostaza.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/micropique/rey.jpg" },
      { name: "Navy Blue", hex: "#000080", image: "/assets/products/micropique/navyblue.jpg" },
      { name: "Naranja NeÃ³n", hex: "#FF7700", image: "/assets/products/micropique/naranja-neon.jpg" },
      { name: "Naranja", hex: "#FF6200", image: "/assets/products/micropique/naranja.jpg" },
      { name: "Rosa NeÃ³n", hex: "#FF17DF", image: "/assets/products/micropique/rosa-neon.jpg" },
      { name: "Amarillo", hex: "#FFFF00", image: "/assets/products/micropique/amarillo.jpg" },
      { name: "Verde NeÃ³n", hex: "#39FF14", image: "/assets/products/micropique/verde-neon.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/micropique/negro.jpg" },
      { name: "Verde Bandera", hex: "#006847", image: "/assets/products/micropique/bandera.jpg" },
      { name: "Verde Botella", hex: "#008000", image: "/assets/products/micropique/verde.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/micropique/rojo.jpg" }
    ]
  },
  {
    id: "prod_micropique_fusionado",
    title: "Micropique Fusionado",
    unit: "Kilo",
    thumbnail: "/assets/products/mpfusionado/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 150.00, mayoreo: 145.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_microtrix",
    title: "Microtrix",
    unit: "Kilo",
    thumbnail: "/assets/products/microtrix/blanco.jpg",
    description: "Tejido de alta elasticidad y recuperaciÃ³n, perfecto para prendas ajustadas y de alto impacto.",
    composicion: "PoliÃ©ster / Spandex",
    gramaje: "180",
    ancho: "1.60m",
    rendimiento: 3.5,
    singleColor: true,
    prices: { menudeo: 150.00, mayoreo: 145.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivo / Licra"
  },
  {
    id: "prod_miky",
    title: "Miky",
    unit: "Kilo",
    thumbnail: "/assets/products/miky/blanco.png",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_monaco",
    title: "Monaco",
    unit: "Kilo",
    thumbnail: "/assets/products/monaco/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_nagasaky",
    title: "Nagasaky",
    unit: "Kilo",
    thumbnail: "/assets/products/nagasaki/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 135.00, mayoreo: 130.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_panal_nitro",
    title: "Panal Nitro",
    unit: "Kilo",
    thumbnail: "/assets/products/117.jpg", 
    description: "Tejido tÃ©cnico avanzado para control de humedad extremo.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.2,
    singleColor: true,
    prices: { menudeo: 185.00, mayoreo: 180.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_panal_plus",
    title: "Panal Plus",
    unit: "Kilo",
    thumbnail: "/assets/products/118.jpg", 
    description: "Mayor cuerpo y estructura para prendas que requieren forma.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 3.7,
    singleColor: true,
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_phoenix",
    title: "Phoenix",
    unit: "Kilo",
    thumbnail: "/assets/products/phoenix/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 95.00, mayoreo: 90.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_pique_lacoste",
    title: "Pique Lacoste",
    unit: "Kilo",
    thumbnail: "/assets/products/pique-lacoste/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 140.00, mayoreo: 135.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_pique_vera",
    title: "PiquÃ© Vera",
    unit: "Kilo",
    thumbnail: "/assets/products/113.jpg", 
    description: "TecnologÃ­a Dry-Fit con textura suave y resistente.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.3,
    prices: { menudeo: 110.00, mayoreo: 105.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n",
    colors: [
      { name: "Camel", hex: "#C19A6B", image: "/assets/products/pique-vera/camel.jpg" },
      { name: "Oro Viejo", hex: "#B08D57", image: "/assets/products/pique-vera/oro-viejo.jpg" },
      { name: "Mostaza", hex: "#FFC300", image: "/assets/products/pique-vera/mostaza.jpg" },
      { name: "Verde NeÃ³n", hex: "#39FF14", image: "/assets/products/pique-vera/verde-neon.jpg" },
      { name: "Amarillo NeÃ³n", hex: "#CCFF00", image: "/assets/products/pique-vera/amarillo-neon.jpg" },
      { name: "Turquesa", hex: "#40E0D0", image: "/assets/products/pique-vera/turquesa.jpg" },
      { name: "Aqua", hex: "#00FFFF", image: "/assets/products/pique-vera/aqua.jpg" },
      { name: "Rosa NeÃ³n", hex: "#FF6EC7", image: "/assets/products/pique-vera/rosa-neon.jpg" },
      { name: "Magenta", hex: "#FF00FF", image: "/assets/products/pique-vera/magenta.jpg" },
      { name: "Militar", hex: "#4B5320", image: "/assets/products/pique-vera/militar.jpg" },
      { name: "Botella", hex: "#006A4E", image: "/assets/products/pique-vera/botella.jpg" },
      { name: "Verde Bandera", hex: "#006847", image: "/assets/products/pique-vera/verde-bandera.jpg" },
      { name: "Cielo", hex: "#87CEEB", image: "/assets/products/pique-vera/cielo.jpg" },
      { name: "Menta", hex: "#98FF98", image: "/assets/products/pique-vera/menta.jpg" },
      { name: "Vino", hex: "#722F37", image: "/assets/products/pique-vera/vino.jpg" },
      { name: "Lila", hex: "#C8A2C8", image: "/assets/products/pique-vera/lila.jpg" },
      { name: "Naranja", hex: "#FF6F00", image: "/assets/products/pique-vera/naranja.jpg" },
      { name: "Uva", hex: "#6F2DA8", image: "/assets/products/pique-vera/uva.jpg" },
      { name: "PetrÃ³leo", hex: "#005F6A", image: "/assets/products/pique-vera/petroleo.jpg" },
      { name: "Rosa Pastel", hex: "#FFD1DC", image: "/assets/products/pique-vera/rosa-pastel.jpg" },
      { name: "Rosa Baby", hex: "#F4C2C2", image: "/assets/products/pique-vera/rosa-baby.jpg" },
      { name: "Palo Rosa", hex: "#D69A9A", image: "/assets/products/pique-vera/palo-rosa.jpg" },
      { name: "Fiusha", hex: "#FF00CB", image: "/assets/products/pique-vera/fiusha.jpg" },
      { name: "Light Navy", hex: "#4A6B8C", image: "/assets/products/pique-vera/ligth-navy.jpg" },
      { name: "Dark Navy", hex: "#000033", image: "/assets/products/pique-vera/dark-navy.jpg" },
      { name: "Gris Medio", hex: "#808080", image: "/assets/products/pique-vera/gris-medio.jpg" },
      { name: "Oxford", hex: "#494949", image: "/assets/products/pique-vera/oxford.jpg" },
      { name: "Gris Perla", hex: "#E6E6E6", image: "/assets/products/pique-vera/gris-perla.jpg" },
      { name: "Mango", hex: "#FFD21C", image: "/assets/products/pique-vera/mango.jpg" },
      { name: "Canario", hex: "#FFE700", image: "/assets/products/pique-vera/canario.jpg" },
      { name: "Caqui", hex: "#C3B091", image: "/assets/products/pique-vera/caqui.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/pique-vera/negro.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/pique-vera/rojo.jpg" },
      { name: "Rey", hex: "#1434A4", image: "/assets/products/pique-vera/rey.jpg" }
    ]
  },
  {
    id: "prod_pique-vera-sport",
    title: "Pique Vera Sport",
    unit: "Kilo",
    thumbnail: "/assets/products/sport.jpeg",
    description: "Versatilidad total para cualquier disciplina deportiva.",
    composicion: "100% PoliÃ©ster",
    gramaje: "145",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true,
    prices: { menudeo: 140.00, mayoreo: 135.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_pixel",
    title: "Pixel",
    unit: "Kilo",
    thumbnail: "/assets/products/pixel/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 155.00, mayoreo: 150.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_polar",
    title: "Polar",
    unit: "Kilo", 
    unidadesPorRollo: 25, 
    thumbnail: "/assets/products/polar/vino.jpg", 
    description: "Tela tÃ©rmica de alto rendimiento con tecnologÃ­a anti-pilling. Es ideal desde la confecciÃ³n de pijamas y mamelucos hasta la creaciÃ³n de cobijas, frazadas, y ropa para mascotas.",
    composicion: "100% PoliÃ©ster", 
    gramaje: "280", 
    ancho: "1.60m",
    rendimiento: 2.5, 
    singleColor: false, 
    prices: { menudeo: 120.00, mayoreo: 115.00 }, 
    hasRollo: true,
    origin: "Importado",
    category: "LÃ­nea Invernal",
    colors: [
      { name: "Verde Botella", hex: "#004B23", image: "/assets/products/polar/verdebotella.jpg" },
      { name: "Verde Militar", hex: "#4B5320", image: "/assets/products/polar/verdemilitar.jpg" },
      { name: "Palo Rosa", hex: "#D69A9A", image: "/assets/products/polar/palorosa.jpg" },
      { name: "Azul Rey", hex: "#1434A4", image: "/assets/products/polar/azulrey.jpg" },
      { name: "Vino", hex: "#5C1527", image: "/assets/products/polar/vino.jpg" },
      { name: "Marino", hex: "#1A243A", image: "/assets/products/polar/marino.jpg" },
      { name: "Fiusha", hex: "#E01B6A", image: "/assets/products/polar/fiusha.jpg" },
      { name: "Negro", hex: "#111111", image: "/assets/products/polar/negro.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/polar/rojo.jpg" },
      { name: "Blanco", hex: "#F8F9FA", image: "/assets/products/polar/blanco.jpg" }
    ]
  },
  {
    id: "prod_saturno",
    title: "Saturno",
    unit: "Kilo",
    thumbnail: "/assets/products/saturno/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 165.00, mayoreo: 160.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_super_trix",
    title: "Super Trix",
    unit: "Kilo",
    thumbnail: "/assets/products/supertrix/blanco.jpg",
    description: "Tela deportiva especializada, ideal para procesos de sublimaciÃ³n de alta definiciÃ³n.",
    composicion: "100% PoliÃ©ster",
    gramaje: "140",
    ancho: "1.60m",
    rendimiento: 4.0,
    singleColor: true, 
    prices: { menudeo: 175.00, mayoreo: 170.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },
  {
    id: "prod_sportok_escolar",
    title: "Sportok",
    unit: "Kg", 
    unidadesPorRollo: 25, 
    thumbnail: "/assets/products/sportock-/blanco-1.jpg", 
    description: "Textil 100% poliÃ©ster de alta resistencia con acabado semi-brillante e interior tÃ©rmico afelpado. La tela estÃ¡ndar para pants, sudaderas y uniformes escolares. No se arruga y es de fÃ¡cil lavado.",
    composicion: "100% PoliÃ©ster (Interior Afelpado)",
    gramaje: "260", 
    ancho: "1.60m",
    rendimiento: 2.4, 
    prices: { menudeo: 80.00, mayoreo: 75.00 },
    hasRollo: true,
    category: "Escolar / Deportivo",
    origin: "importado",
    colors: [
      { name: "Francia", hex: "#1F3A93", image: "/assets/products/sportock-/francia-1.jpg" },
      { name: "Marino Claro", hex: "#003366", image: "/assets/products/sportock-/marinoclaro-1.jpg" },
      { name: "Magenta", hex: "#FF00FF", image: "/assets/products/sportock-/magenta.jpg" },
      { name: "Chedron", hex: "#8A3324", image: "/assets/products/sportock-/chedron-1.jpg" },
      { name: "Acero", hex: "#778899", image: "/assets/products/sportock-/acero-1.jpg" },
      { name: "Naranja Pastel", hex: "#FFB347", image: "/assets/products/sportock-/naranja-pastel.jpg" },
      { name: "Amarillo Pastel", hex: "#FDFD96", image: "/assets/products/sportock-/amarillo-pastel-.jpg" },
      { name: "PetrÃ³leo", hex: "#005F6A", image: "/assets/products/sportock-/petroleo.jpg" },
      { name: "Oro Viejo", hex: "#B08D57", image: "/assets/products/sportock-/oro-viejo.jpg" },
      { name: "Mostaza", hex: "#FFC300", image: "/assets/products/sportock-/mostaza.jpg" },
      { name: "Palo de Rosa", hex: "#D69A9A", image: "/assets/products/sportock-/paloderosa.jpg" },
      { name: "Jade", hex: "#00A86B", image: "/assets/products/sportock-/jade.jpg" },
      { name: "Lila", hex: "#C8A2C8", image: "/assets/products/sportock-/lila.jpg" },
      { name: "Bugambilia", hex: "#E0115F", image: "/assets/products/sportock-/bugambilia-1.jpg" },
      { name: "Fiusha", hex: "#FF00CB", image: "/assets/products/sportock-/fresa-1.jpg" },
      { name: "Gris Baby", hex: "#D3D3D3", image: "/assets/products/sportock-/gris baby.jpg" },
      { name: "Perla", hex: "#EAE0C8", image: "/assets/products/sportock-/perla-1.jpg" },
      { name: "Medio", hex: "#808080", image: "/assets/products/sportock-/grismedio-1.jpg" },
      { name: "Oxford", hex: "#494949", image: "/assets/products/sportock-/oxford-1.jpg" },
      { name: "Caqui", hex: "#C3B091", image: "/assets/products/sportock-/caqui.jpg" },
      { name: "Beige", hex: "#F5F5DC", image: "/assets/products/sportock-/beige.jpg" },
      { name: "Cafe", hex: "#4B3621", image: "/assets/products/sportock-/cafe-1.jpg" },
      { name: "Camel", hex: "#C19A6B", image: "/assets/products/sportock-/camel.jpg" },
      { name: "Rosa Pastel", hex: "#FFD1DC", image: "/assets/products/sportock-/rosa-1.jpg" },
      { name: "Turquesa", hex: "#40E0D0", image: "/assets/products/sportock-/turquesa.jpg" },
      { name: "Aqua", hex: "#00FFFF", image: "/assets/products/sportock-/azulpastel-1.jpg" },
      { name: "Menta", hex: "#98FF98", image: "/assets/products/sportock-/menta.jpg" },
      { name: "Morado", hex: "#800080", image: "/assets/products/sportock-/morado-1.jpg" },
      { name: "Uva", hex: "#6F2DA8", image: "/assets/products/sportock-/vinooscuro-1.jpg" },
      { name: "Rosa Baby", hex: "#F4C2C2", image: "/assets/products/sportock-/rosa-baby-1.jpg" },
      { name: "Cielo", hex: "#87CEEB", image: "/assets/products/sportock-/cielo-1.jpg" },
      { name: "Naranja NeÃ³n", hex: "#FF5F1F", image: "/assets/products/sportock-/naranjaneon-1.jpg" },
      { name: "Rosa NeÃ³n", hex: "#FF6EC7", image: "/assets/products/sportock-/rosa neon.jpg" },
      { name: "Verde NeÃ³n", hex: "#39FF14", image: "/assets/products/sportock-/verde-neon-1.jpg" },
      { name: "Amarillo NeÃ³n", hex: "#CCFF00", image: "/assets/products/sportock-/amarilloneon-1.jpg" },
      { name: "Pistache", hex: "#93C572", image: "/assets/products/sportock-/pistache-1.jpg" },
      { name: "Manzana", hex: "#8DB600", image: "/assets/products/sportock-/manzana-1.jpg" },
      { name: "Militar", hex: "#4B5320", image: "/assets/products/sportock-/militar-1.jpg" },
      { name: "Botella", hex: "#006A4E", image: "/assets/products/sportock-/botella.jpg" },
      { name: "Bandera", hex: "#006847", image: "/assets/products/sportock-/bandera-1.jpg" },
      { name: "Naranja", hex: "#FF6F00", image: "/assets/products/sportock-/naranja-1.jpg" },
      { name: "Rey", hex: "#1434A4", image: "/assets/products/sportock-/rey.jpg" },
      { name: "Mango", hex: "#FFD21C", image: "/assets/products/sportock-/amarillomabgo-1.jpg" },
      { name: "Canario", hex: "#FFE700", image: "/assets/products/sportock-/amarillocanario-1.jpg" },
      { name: "Rojo", hex: "#C40233", image: "/assets/products/sportock-/rojo-1.jpg" },
      { name: "Rojo Quemado", hex: "#8B0000", image: "/assets/products/sportock-/rojo-quemado.jpg" },
      { name: "Negro", hex: "#050505", image: "/assets/products/sportock-/negro-1.jpg" },
      { name: "Blanco", hex: "#FFFFFF", image: "/assets/products/sportock-/blanco-1.jpg" },
      { name: "Marino", hex: "#000080", image: "/assets/products/sportock-/marino-1.jpg" }
    ]
  },
  {
    id: "prod_torneo",
    title: "Torneo",
    unit: "Kilo",
    thumbnail: "/assets/products/115.jpg", 
    description: "El estÃ¡ndar en durabilidad para torneos exigentes.",
    composicion: "100% PoliÃ©ster",
    gramaje: "150",
    ancho: "1.60m",
    rendimiento: 4.3,
    prices: { menudeo: 125.00, mayoreo: 120.00 },
    hasRollo: true,
    origin: "Importado",
    category: "Deportivas / SublimaciÃ³n"
  },

  // === TELAS AGREGADAS 2026-05 (catalogo extendido del tote oficial) ===
  { id: "prod_bombay", title: "Bombay", unit: "Kilo", thumbnail: "/assets/products/bombay/blanco.jpg", description: "Tela versÃ¡til para confecciÃ³n casual de alta resistencia.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 115, mayoreo: 110 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_cardigan", title: "Cardigan", unit: "Kilo", thumbnail: "/assets/products/cardigan/blanco.jpg", description: "Tela de punto ideal para suÃ©teres y prendas de temporada media.", composicion: "Mixto", gramaje: "140", ancho: "1.60m", rendimiento: 2.2, prices: { menudeo: 130, mayoreo: 120 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Invernal" },
  { id: "prod_chifon", title: "ChifÃ³n", unit: "Kilo", thumbnail: "/assets/products/chifon/blanco.jpg", description: "Tela ligera y vaporosa, ideal para blusas y prendas elegantes.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "90cm", rendimiento: 2.3, prices: { menudeo: 165, mayoreo: 160 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_dublin", title: "Dublin", unit: "Kilo", thumbnail: "/assets/products/dublin/blanco.jpg", description: "Tela econÃ³mica para confecciÃ³n casual.", composicion: "Mixto", gramaje: "N/A", ancho: "1.60m", rendimiento: 3.0, prices: { menudeo: 75, mayoreo: 70 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_felpa_nacional", title: "Felpa Nacional", unit: "Kilo", thumbnail: "/assets/products/felpa_china/marino.jpg", description: "Felpa de fabricaciÃ³n nacional, ideal para sudaderas y pants.", composicion: "Mixto", gramaje: "280", ancho: "1.60m", rendimiento: 2.5, prices: { menudeo: 103, mayoreo: 98 }, hasRollo: true, singleColor: true, origin: "Nacional", category: "LÃ­nea Invernal" },
  { id: "prod_flanel_2", title: "Flanel Nacional", unit: "Kilo", thumbnail: "/assets/products/flanel/cuadro.jpg", description: "Flanel nacional para camisas y prendas de invierno.", composicion: "Mixto", gramaje: "N/A", ancho: "1.60m", rendimiento: 2.5, prices: { menudeo: 103, mayoreo: 98 }, hasRollo: true, singleColor: true, origin: "Nacional", category: "LÃ­nea Invernal" },
  { id: "prod_french_terry", title: "French Terry", unit: "Kilo", thumbnail: "/assets/products/french_terry/gris.jpg", description: "Tela de algodÃ³n con tejido afelpado por dentro, ideal para sudaderas premium.", composicion: "Mixto", gramaje: "N/A", ancho: "1.50m", rendimiento: 2.7, prices: { menudeo: 115, mayoreo: 105 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_gran_bay", title: "Gran Bay", unit: "Kilo", thumbnail: "/assets/products/granbay/blanco.jpg", description: "Tela de excelente caÃ­da para confecciÃ³n casual.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 130, mayoreo: 125 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_interlock", title: "Interlock", unit: "Kilo", thumbnail: "/assets/products/interlock/blanco.jpg", description: "Tela de tejido doble que aporta cuerpo y resistencia.", composicion: "Mixto", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 140, mayoreo: 135 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_jurly", title: "Jurly", unit: "Kilo", thumbnail: "/assets/products/jurly/blanco.jpg", description: "Tela versÃ¡til para confecciÃ³n casual.", composicion: "Mixto", gramaje: "140", ancho: "1.60m", rendimiento: 4.6, prices: { menudeo: 135, mayoreo: 125 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_licra_poliester_byn_rojo", title: "Licra PoliÃ©ster B/N/Rojo", unit: "Kilo", thumbnail: "/assets/products/licra-poliester/colores.jpg", description: "Licra con elasticidad firme en colores bÃ¡sicos.", composicion: "100% PoliÃ©ster con Spandex", gramaje: "265", ancho: "1.60m", rendimiento: 4.7, prices: { menudeo: 115, mayoreo: 110 }, hasRollo: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_macuco", title: "Macuco", unit: "Kilo", thumbnail: "/assets/products/macuco/blanco.jpg", description: "Tela de uso versÃ¡til para confecciÃ³n.", composicion: "Mixto", gramaje: "265", ancho: "1.55m", rendimiento: 2.6, prices: { menudeo: 140, mayoreo: 130 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_mar", title: "Mar", unit: "Kilo", thumbnail: "/assets/products/mar/blanco.jpg", description: "Tela tipo punto para uso casual.", composicion: "Mixto", gramaje: "145", ancho: "1.60m", rendimiento: 4.2, prices: { menudeo: 151, mayoreo: 146 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_memory", title: "Memory", unit: "Kilo", thumbnail: "/assets/products/memory/blanco.jpg", description: "Tela con memoria de forma, mantiene su silueta.", composicion: "Mixto", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 115, mayoreo: 110 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_microfibra", title: "Microfibra", unit: "Kilo", thumbnail: "/assets/products/microfibra/blanco.jpg", description: "Microfibra suave y ligera, ideal para deportiva tÃ©cnica.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 105, mayoreo: 100 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_microfibra_fusionada", title: "Microfibra Fusionada", unit: "Metro", thumbnail: "/assets/products/microfibra-fusionada/blanco.jpg", description: "Microfibra fusionada por metro lineal.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 1.0, prices: { menudeo: 110, mayoreo: 105 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_micro_pique_rey", title: "Micro Pique Rey", unit: "Kilo", thumbnail: "/assets/products/micropique-rey/blanco.jpg", description: "Variante Premium de Micro Pique.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 95, mayoreo: 90 }, hasRollo: true, singleColor: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_micropique_diamante", title: "Micropique Diamante", unit: "Kilo", thumbnail: "/assets/products/micropique-diamante/blanco.jpg", description: "Micropique con textura diamante.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 100, mayoreo: 95 }, hasRollo: true, singleColor: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_milenio_calado", title: "Milenio Calado", unit: "Kilo", thumbnail: "/assets/products/milenio-calado/blanco.jpg", description: "Tela calada para confecciÃ³n de prendas frescas.", composicion: "Mixto", gramaje: "140", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 125, mayoreo: 120 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_oklahoma", title: "Oklahoma", unit: "Kilo", thumbnail: "/assets/products/oklahoma/blanco.jpg", description: "Tela de alta resistencia para confecciÃ³n durable.", composicion: "Mixto", gramaje: "150", ancho: "1.60m", rendimiento: 3.7, prices: { menudeo: 155, mayoreo: 145 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_pique_50_50_blanco", title: "Pique 50/50 Blanco", unit: "Kilo", thumbnail: "/assets/products/pique-50-50/blanco.jpg", description: "Pique 50/50 algodÃ³n-poliÃ©ster en blanco.", composicion: "50% AlgodÃ³n / 50% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 4.2, prices: { menudeo: 120, mayoreo: 115 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_polar_cuadro", title: "Polar Cuadro", unit: "Kilo", thumbnail: "/assets/products/polar-cuadro/blanco.jpg", description: "Polar con textura cuadro, ideal para forros invernales.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 2.5, prices: { menudeo: 115, mayoreo: 100 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Invernal" },
  { id: "prod_punto_de_roma", title: "Punto de Roma", unit: "Kilo", thumbnail: "/assets/products/punto-de-roma/blanco.jpg", description: "Punto de Roma de excelente caÃ­da para vestidos y pantalones.", composicion: "Mixto", gramaje: "145", ancho: "1.60m", rendimiento: 2.5, prices: { menudeo: 103, mayoreo: 98 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_premier", title: "Premier", unit: "Kilo", thumbnail: "/assets/products/premier/blanco.jpg", description: "Tela Premier de calidad superior.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.60m", rendimiento: 1.7, prices: { menudeo: 98, mayoreo: 93 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_rompevientos", title: "Rompevientos", unit: "Kilo", thumbnail: "/assets/products/rompevientos/marino.jpg", description: "Tela tÃ©cnica resistente al viento, ideal para chamarras.", composicion: "100% PoliÃ©ster", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 110, mayoreo: 105 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_saludable_camuflaje_negro", title: "Saludable Camuflaje Negro", unit: "Kilo", thumbnail: "/assets/products/saludable-camuflaje-negro/blanco.jpg", description: "Saludable con estampado camuflaje negro.", composicion: "Mixto", gramaje: "N/A", ancho: "1.50m", rendimiento: 2.3, prices: { menudeo: 29, mayoreo: 27 }, hasRollo: true, singleColor: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_soccer", title: "Soccer", unit: "Kilo", thumbnail: "/assets/products/soccer/blanco.jpg", description: "Tela tÃ©cnica para uniformes deportivos de fÃºtbol.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.70m", rendimiento: 4.2, prices: { menudeo: 120, mayoreo: 115 }, hasRollo: true, singleColor: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_tacto_princesa", title: "Tacto Princesa", unit: "Kilo", thumbnail: "/assets/products/tacto-princesa/rosa.jpg", description: "Tela con tacto suave, ideal para prendas finas.", composicion: "Mixto", gramaje: "140", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 150, mayoreo: 145 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_tafeta", title: "Tafeta", unit: "Kilo", thumbnail: "/assets/products/tafeta/blanco.jpg", description: "Tela tafeta para forros y prendas elegantes.", composicion: "100% PoliÃ©ster", gramaje: "140", ancho: "1.60m", rendimiento: 1.0, prices: { menudeo: 160, mayoreo: 150 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_tafetan", title: "TafetÃ¡n", unit: "Metro", thumbnail: "/assets/products/tafetan/blanco.jpg", description: "TafetÃ¡n por metro lineal.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.50m", rendimiento: 1.0, prices: { menudeo: 105, mayoreo: 100 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_tergal", title: "Tergal", unit: "Metro", thumbnail: "/assets/products/tergal/blanco.jpg", description: "Tela Tergal econÃ³mica por metro.", composicion: "Mixto", gramaje: "N/A", ancho: "1.50m", rendimiento: 1.0, prices: { menudeo: 24, mayoreo: 19 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_timberland_m", title: "Timberland M", unit: "Metro", thumbnail: "/assets/products/timberland/blanco.jpg", description: "Timberland por metro lineal.", composicion: "Mixto", gramaje: "N/A", ancho: "1.50m", rendimiento: 1.0, prices: { menudeo: 33, mayoreo: 28 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_titanium", title: "Titanium", unit: "Metro", thumbnail: "/assets/products/titanium/blanco.jpg", description: "Tela Titanium para confecciÃ³n tÃ©cnica.", composicion: "Mixto", gramaje: "N/A", ancho: "1.50m", rendimiento: 1.0, prices: { menudeo: 40, mayoreo: 38 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_toallin", title: "Toallin", unit: "Kilo", thumbnail: "/assets/products/toallin/blanco.jpg", description: "Tela tipo toalla absorbente.", composicion: "Mixto", gramaje: "N/A", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 57, mayoreo: 52 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_tricot", title: "Tricot", unit: "Kilo", thumbnail: "/assets/products/tricot/blanco.jpg", description: "Tela de tejido tricot para confecciÃ³n casual.", composicion: "Mixto", gramaje: "150", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 105, mayoreo: 100 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_university_m", title: "University M", unit: "Metro", thumbnail: "/assets/products/university/blanco.jpg", description: "Tela University por metro, uso casual.", composicion: "Mixto", gramaje: "150", ancho: "1.60m", rendimiento: 1.0, prices: { menudeo: 115, mayoreo: 110 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
  { id: "prod_vinipiel", title: "Vinipiel", unit: "Metro", thumbnail: "/assets/products/vinipiel/negro.jpg", description: "Vinipiel para tapicerÃ­a y prendas tÃ©cnicas.", composicion: "SintÃ©tico", gramaje: "N/A", ancho: "3.40m", rendimiento: 1.0, prices: { menudeo: 30, mayoreo: 28 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Especial" },
  { id: "prod_vera_sport_metro", title: "Vera Sport Metro", unit: "Metro", thumbnail: "/assets/products/vera-sport/blanco.jpg", description: "Vera Sport por metro lineal.", composicion: "100% PoliÃ©ster", gramaje: "N/A", ancho: "1.60m", rendimiento: 1.0, prices: { menudeo: 60, mayoreo: 55 }, hasRollo: true, singleColor: true, origin: "Importado", category: "Deportivas / SublimaciÃ³n" },
  { id: "prod_zarga_mt", title: "Zarga MT", unit: "Kilo", thumbnail: "/assets/products/zarga/blanco.jpg", description: "Tela Zarga MT para confecciÃ³n casual.", composicion: "Mixto", gramaje: "145", ancho: "1.60m", rendimiento: 4.3, prices: { menudeo: 140, mayoreo: 135 }, hasRollo: true, singleColor: true, origin: "Importado", category: "LÃ­nea Casual" },
];